[tools]
node = "latest"
watchexec = "latest"
usage = "latest"
go = "latest"
python = "3.9.10"
deno = "latest"
java = "latest"
gcloud = "latest"
lua = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node"]
